### ISSUE TITLE
Create ORM entities based on JSON schema

### ISSUE THREAD

**Issue by JHGitty** [janephp/jane#11]
What's about creation of Doctrine2 entities based on JSON schema?

**Comment by JHGitty** [comment]
This feature could also be useful for other ORM. For example Propel2.
http://propelorm.org

**Comment by joelwurtz** [comment]
This is possible, but not my main focus on this library as often a database model is different from an api model.

If someone send me a pull request to add this (in an optional way), i will be glad to merge it.

**Comment by JHGitty** [comment]
related to https://github.com/KnpLabs/KnpJsonSchemaBundle/issues/23

**Comment by joelwurtz** [comment]
Not wanted feature in this lib, i will not have time to add this and maintain, however this lib is easily extendable if someone wants to do something that support this feature.
