### ISSUE TITLE
Boolean value getter should look like is*

### ISSUE THREAD

**Issue by sagikazarmark** [janephp/jane#13]
Instead of getSomething it could be isSomething.

**Comment by sagikazarmark** [comment]
Hm, this is not something easy after all, as in some cases it could be hasser, not isser.

**Comment by sagikazarmark** [comment]
Okay, finally I found a probably acceptable idea: boolean values are not necessarily accessible through issers/hassers. For example state markers like `useHttps` might be shouldUseHttps.

The easiest solution would be to adhere the current behavior based on the parameter name: if it starts with "is", "has" or "should" then replace "get" with that keyword in the getter generator.

WDYT @joelwurtz ?

**Comment by joelwurtz** [comment]
It would be nice to have this, but the value of work compared to the value of this feature put this in a "nice to have" and i want to do others thing before that (like the DateTime thing).

**Comment by sagikazarmark** [comment]
I don't think it would cost too much work. Basically I would mess around with the method name prefix here:

https://github.com/jolicode/jane/blob/master/src/Generator/Model/GetterSetterGenerator.php#L34

Check the variable name, if it starts with is, has, should (?), replace get with that prefix.

**Comment by joelwurtz** [comment]
There are other parts where the method is used like here : https://github.com/jolicode/jane/blob/master/src/Generator/Normalizer/DenormalizerGenerator.php#L103

And don't want to duplicate the logic on guessing the prefix, it would be better to guess at the start and to write the mode for setting / getting as a parameter in the Property metadata.

**Comment by sagikazarmark** [comment]
Okay, let's put it on hold then.

**Comment by joelwurtz** [comment]
Closing this as i won't fix it unless there is a PR about it.
