### ISSUE TITLE
Automatically guess directory from class-name

### ISSUE THREAD

**Issue by moufmouf** [janephp/jane#18]
Hey Jolicoders!

Just noticed the command asks for both the class name and the directory where to write the files.
I just wrote this very small package that can find the directory based on the classname (and composer.json file): https://github.com/thecodingmachine/classname-mapper (_Shameless package auto-promotion_ :) )

This could make Jane even easier to use.

**Comment by joelwurtz** [comment]
I actually want to lower the dependency number on this library, but will certainly add this when i will separate this library with a runtime one, like said in https://github.com/jolicode/jane-openapi/issues/19

**Comment by joelwurtz** [comment]
Don't really want to add a new dependency, setting this is only a single line, the cost is higher than the gain, so i will not support this.
