### ISSUE TITLE
Read-only properties

### ISSUE THREAD

**Issue by sagikazarmark** [janephp/jane#28]
Read-only properties should not be normalized?

**Comment by joelwurtz** [comment]
Don't think there is read only possibility in json schema ?

**Comment by sagikazarmark** [comment]
Possibly wrong repo again? Swagger supports read-only, not sure about JSON Schema.

**Comment by joelwurtz** [comment]
Closing this as it's related to openapi, i will not support this ATM unless there is a demand about it on the new library. Even if it's in the documentation i didn't see any api using this flag.
