### ISSUE TITLE
Jane does not work well with symfony serializer

### ISSUE THREAD

**Issue by sagikazarmark** [janephp/jane#33]
I tried Jane with adding the normalizers  and the encoder to the core Symfony normalizer. Unfortunately they haven't played nicely together: I ended up having empty objects when deserializing. I traced the problem back to the fact that denormalizers receive $data arrays, not objects.

Any idea how to solve this issue?

**Comment by sagikazarmark** [comment]
Found the problem. If anyone else meets with it: by default, the JsonDecoder receives it's first argument as true, which means it creates associative array instead of object. Not sure how this can effectively be solved without breaking compatibility with other parts of the system.

**Comment by sagikazarmark** [comment]
Hm, looking at other normalizers: they always use array, and convert object to array. Would it make sense in jane?

**Comment by sagikazarmark** [comment]
Hm, here is another idea: create a simple, generic accessor stuff (or use property accessor?) which decides about the given structure if it is array or stdClass.

What we need: a hasser to check if a property exists and a getter. That way we could use jane in symfony with the core serializer. WDYT @joelwurtz ?

**Comment by joelwurtz** [comment]
Distinguish between array / object allow to disting between map and array in a better way that doing some random guess with keys which is needed for better encoding, using an array will make things horrible for empty object which would be encoded as an empty array (and it would be wrong with the spec), don't think i will ever change this.

My opinion is that current way of dealing with array is wrong in symfony, and lead to many errors in many apis.
