### ISSUE TITLE
Version 1.5.0 is broken

### ISSUE THREAD

**Issue by shadowhand** [janephp/jane#45]
Without a config file, version 1.5.0 cannot be used. This was fixed in b8cbdfbfbe00f58e65a911a6daa353e1664a799d but no 1.5.1 fix has been released.

This can be done with with a disconnected tag:

```
git checkout v1.5.0
git cherry-pick b8cbdfbfbe00f58e65a911a6daa353e1664a799d
git tag v1.5.1
git push --tags
```

**Comment by shadowhand** [comment]
Alternatively, just release version 1.6.0. 😎

**Comment by joelwurtz** [comment]
I will do your first solution, as i have upgrade the php version to 5.5 for some needs and so this can be a BC break for some people.

I will certainly throw a 2.0 in the summer as well as reviewing some others libs that i work on since i will have time to spare for this :)

**Comment by joelwurtz** [comment]
should be good, reopen it if not.

**Comment by shadowhand** [comment]
Thanks!
