### ISSUE TITLE
Referenced class does not exist

### ISSUE THREAD

**Issue by mburtscher** [janephp/jane#53]
In `Jane.php` you are referencing a class with the FQCN `Joli\Jane\Runtime\Encoder\RawEncoder`. However, this class does not exist in the `jane/runtime` package?

**Comment by joelwurtz** [comment]
It was used before, not needed anymore since symfony 3.1, will remove it from the namespace simple mistake :)

**Comment by mburtscher** [comment]
Ahh OK, it's unused. Sorry to bother you with that ;-) Then I'll check the usages in `docker-php/docker-php` because that one crashes with your recent version because of `RawEncoder`…

**Comment by joelwurtz** [comment]
Should not since it's on a new version of the runtime ? or maybe it's use the wrong version ?

**Comment by mburtscher** [comment]
I've updated dependencies but missed it was using the `RawEncoder` internally. Just adapting the implementation to work without it…

**Comment by joelwurtz** [comment]
No, thanks for the notification i will remove this

**Comment by joelwurtz** [comment]
(With the last version of jane it uses the normalization instead of serialization in the sub process of the encoding / decoding, thanks to update that was done to symfony 3.1)
