### ISSUE TITLE
[4.0] Binary strings & PHP type hinting

### ISSUE THREAD

**Issue by SamMousa** [janephp/jane#56]
In the latest commits of 4.0 type hints are added.

For the type defined in a schema a binary string the PHP typehint `string` is used.
I propose to change this to a different type: `StreamInterface`.
This is always available (it is required via: `runtime > league/uri > psr/http-message`).
It supports strings of any size (binary strings tend to be large since they often represent files).

A simple wrapper could be created to easily convert any string to an object instance that implements `StreamInterface`.

**Comment by joelwurtz** [comment]
:+1: No need for the wrapper as i use a stream factory that transform string / resource / StreamInterface into a StreamInterface (Same could be done for the async version)

So a binary string will have multiple types in the doc block `string|resource|StreamInterface` and no strong type defined on the method

**Comment by SamMousa** [comment]
Are you sure? How did this happen?
https://github.com/docker-php/docker-php-api/blob/4.1.35/src/Resource/ImageResourceTrait.php#L89

**Comment by joelwurtz** [comment]
No you are right, `string` type should be there and binary type should be supported like the file type, see https://github.com/janephp/janephp/blob/master/src/OpenApi/Generator/Parameter/BodyParameterGenerator.php#L115

**Comment by SamMousa** [comment]
Should this be closed or does it still need fixing?

**Comment by joelwurtz** [comment]
Need to be fixed

**Comment by joelwurtz** [comment]
Fixed in https://github.com/janephp/janephp/commit/8c2a09c02ace0a7dceac2320d461cf75faf0c105
